[package]
name = "cartridge-macros"
version = "0.0.0"
authors = ["iovxw <iovxw@outlook.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"] }
quote = "1.0"
lazy_static = "1.0"
proc-macro-crate = "0.1"

